version: "2"
services:
  development:
    build: .
    environment:
      - APP_ENV=development
      - DISPLAY=$DISPLAY
      - SDL_VIDEODRIVER=x11
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: bundle exec ruby app.rb

  test:
    build: .
    environment:
      - APP_ENV=test
    command: bundle exec rspec spec



